# Generated by Django 2.1.1 on 2019-02-24 17:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Second_name')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(100)], verbose_name='Age')),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=1, verbose_name='Gender')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Second_name')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(50)], verbose_name='Age')),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=1, verbose_name='Gender')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Phone')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Parent', verbose_name='Padre')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
