# Generated by Django 2.0 on 2019-01-16 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20190115_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name_plural': 'Parents'},
        ),
    ]
