# Generated by Django 2.0 on 2019-01-20 18:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20190115_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
