# Generated by Django 2.1.1 on 2019-02-24 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First_Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last_name')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Age')),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=1, verbose_name='Gender')),
                ('birth', models.DateField(verbose_name='Birth')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
            },
        ),
    ]
