# Generated by Django 2.0 on 2019-01-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(verbose_name=100)),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=1)),
                ('birth', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=8)),
            ],
        ),
    ]
