# Generated by Django 2.0 on 2019-01-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='age',
            field=models.IntegerField(),
        ),
    ]
