# Generated by Django 2.1.1 on 2019-02-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professors', '0001_initial'),
        ('grades', '0001_initial'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('M', 'Morning'), ('T', 'Evening'), ('N', 'Night')], max_length=1, verbose_name='Type')),
                ('grade', models.ManyToManyField(to='grades.Grade', verbose_name='Grade')),
                ('professor', models.ManyToManyField(to='professors.Professor', verbose_name='Professor')),
                ('registration', models.ManyToManyField(to='enrollments.Registration', verbose_name='Registration')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
