# Generated by Django 2.0 on 2019-01-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0002_remove_assignature_description'),
        ('professors', '0001_initial'),
        ('enrollments', '0002_registration_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('m', 'Morning'), ('e', 'Evening'), ('n', 'Night')], max_length=1)),
                ('grade', models.ManyToManyField(to='grades.Assignature')),
                ('professor', models.ManyToManyField(to='professors.Professor')),
                ('registration', models.ManyToManyField(to='enrollments.Registration')),
            ],
        ),
    ]
